config/routes.rb
Rails.application.routes.draw do
  resources :ratings
  resources :properties
  resources :accounts
  get "welcome/index"
  # get "properties/rating_count"
  # get '/rating_count', to: 'properties#rating_count'
  root to: "welcome#index"
end

app/models/account.rb
class Account < ApplicationRecord
  # has_many :properties
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/property.rb
class Property < ApplicationRecord
  # belongs_to :account
  # has_one :rating
  geocoded_by :address
  after_validation :geocode
  has_one_attached :avatar
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :property
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]

  # GET /accounts
  def index
    @accounts = Account.all
    render json: @accounts
  end

  # GET /accounts/1
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  def create
    @account = Account.new(account_params)

    if @account.save
      render json: @account, status: :created, location: @account
    else
      render json: @account.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /accounts/1
  def update
    if @account.update(account_params)
      render json: @account
    else
      render json: @account.errors, status: :unprocessable_entity
    end
  end

  # DELETE /accounts/1
  def destroy
    @account.destroy
    # redirect_to accounts_url, notice: "Account was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:first_name, :last_name, :email)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
end

app/controllers/properties_controller.rb
require 'http'

class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy ]

  # GET /properties
  def index
    @properties = Property.all.sort_by {|pr| pr.rating}.reverse
    render json: @properties
  end

  # GET /properties/1
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  def set_fake_coordinate
    if @property.latitude.present?
      @property.fake_latitude = @property.latitude + [-0.0003, -0.0002, -0.0001, 0.0001, 0.0002, 0.0003].sample
      @property.fake_longitude = @property.longitude + [-0.0003, -0.0002, -0.0001, 0.0001, 0.0002, 0.0003].sample
      @property.save
    else
      render json: @property.errors, status: :unprocessable_entity
    end
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  def create
    @property = Property.create(property_params)
    set_fake_coordinate
    if @property.save
      # redirect_to @property, notice: "Property was successfully created."
      render json: @property, status: :created, location: @property
    else
      # render :new, status: :unprocessable_entity
      render json: @property.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /properties/1
  def update
    if @property.update(property_params)
    #   redirect_to @property, notice: "Property was successfully updated."
    # else
    #   render :edit, status: :unprocessable_entity
      render json: @property
    else
      render json: @property.errors, status: :unprocessable_entity
    end
  end

  # DELETE /properties/1
  def destroy
    @property.destroy
    # redirect_to properties_url, notice: "Property was successfully destroyed.", status: :see_other
  end

  # def rating_count
  #   @rating = HTTP.get("https://api.mapbox.com/search/v1/forward/%E3%82%AF%E3%83%AA%E3%83%8B%E3%83%83%E3%82%AF?language=ja&limit=50&proximity=132.754883,35.366889&bbox=132.74488300000002,35.356889,132.764883,35.376889&country=JP&access_token=pk.eyJ1IjoiaXJpbmFzayIsImEiOiJjbDIwOHhrbm0wdWJlM2pxZDNvN3A5NHNzIn0.M37Dun7-7tjVc9C0O82lpw").to_s
  #   # HTTP.get("https://github.com").to_s
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:title, :price, :rooms, :bathrooms, :avatar, :address, :longitude, :latitude, :fake_latitude, :fake_longitude, :rating)
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: %i[ show edit update destroy ]

  # GET /ratings or /ratings.json
  def index
    @ratings = Rating.all
    render json: @ratings
  end

  # GET /ratings/1 or /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings or /ratings.json
  def create
    @rating = Rating.new(rating_params)

    # respond_to do |format|
    #   if @rating.save
    #     format.html { redirect_to rating_url(@rating), notice: "Rating was successfully created." }
    #     format.json { render :show, status: :created, location: @rating }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @rating.errors, status: :unprocessable_entity }
    #   end
    # end

    if @property.save
      render json: @rating, status: :created, location: @rating
    else
      render json: @rating.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /ratings/1 or /ratings/1.json
  def update
    # respond_to do |format|
    #   if @rating.update(rating_params)
    #     format.html { redirect_to rating_url(@rating), notice: "Rating was successfully updated." }
    #     format.json { render :show, status: :ok, location: @rating }
    #   else
    #     format.html { render :edit, status: :unprocessable_entity }
    #     format.json { render json: @rating.errors, status: :unprocessable_entity }
    #   end
    # end

    if @rating.update(rating_params)
        render json: @rating
    else
        render json: @rating.errors, status: :unprocessable_entity
    end
  end

  # DELETE /ratings/1 or /ratings/1.json
  def destroy
    @rating.destroy

    # respond_to do |format|
    #   format.html { redirect_to ratings_url, notice: "Rating was successfully destroyed." }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rating_params
      params.require(:rating).permit(:location_rating)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/accounts/_account.html.erb
<div id="<%= dom_id account %>">
  <p>
    <strong>First name:</strong>
    <%= account.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= account.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= account.email %>
  </p>

</div>

app/views/accounts/_form.html.erb
<%= form_with(model: account) do |form| %>
  <% if account.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Show this account", @account %> |
  <%= link_to "Back to accounts", accounts_path %>
</div>

app/views/accounts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Accounts</h1>

<div id="accounts">
  <% @accounts.each do |account| %>
    <%= render account %>
    <p>
      <%= link_to "Show this account", account %>
    </p>
  <% end %>
</div>

<%= link_to "New account", new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render "form", account: @account %>

<br>

<div>
  <%= link_to "Back to accounts", accounts_path %>
</div>

app/views/accounts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @account %>

<div>
  <%= link_to "Edit this account", edit_account_path(@account) %> |
  <%= link_to "Back to accounts", accounts_path %>

  <%= button_to "Destroy this account", @account, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vuerails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application' %>
    <!--
      If using a TypeScript entrypoint file:
        vite_typescript_tag 'application'

      If using a .jsx or .tsx entrypoint, add the extension:
        vite_javascript_tag 'application.jsx'

      Visit the guide for more information: https://vite-ruby.netlify.app/guide/rails
    -->

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_with(model: property) do |form| %>
  <% if property.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :rooms, style: "display: block" %>
    <%= form.number_field :rooms %>
  </div>

  <div>
    <%= form.label :bathrooms, style: "display: block" %>
    <%= form.number_field :bathrooms %>
  </div>

  <div>
    <%= form.label :avatar, style: "display: block" %>
    <%= form.file_field :avatar %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :latitude, style: "display: block" %>
    <%= form.number_field :latitude %>
  </div>

  <div>
    <%= form.label :longitude, style: "display: block" %>
    <%= form.number_field :longitude %>
  </div>

  <div>
    <%= form.label :account_id, style: "display: block" %>
    <%= form.number_field :account_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= javascript_include_tag('/app/frontend/entrypoints/components/test.js') %>

app/views/properties/_property.html.erb
<div id="<%= dom_id property %>">
  <p>
    <strong>Title:</strong>
    <%= property.title %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= property.price %>
  </p>

  <p>
    <strong>Rooms:</strong>
    <%= property.rooms %>
  </p>

  <p>
    <strong>Bathrooms:</strong>
    <%= property.bathrooms %>
  </p>

  <p>
    <strong>Avatar:</strong>
    <%= image_tag property.avatar.representation(resize_to_limit: [100, 100]) %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= property.rating&.location_rating %>
  </p>

</div>

app/views/properties/edit.html.erb
<h1>Editing property</h1>

<%= render "form", property: @property %>

<br>

<div>
  <%= link_to "Show this property", @property %> |
  <%= link_to "Back to properties", properties_path %>
</div>

app/views/properties/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Properties</h1>

<div id="properties">
  <% @properties.each do |property| %>
    <%= render property %>
    <p>
      <%= js_map [{latitude: 37.7829, longitude: -122.4190}] %>
      <%= link_to "Show this property", property %>
    </p>
  <% end %>
</div>

<%= link_to "New property", new_property_path %>

app/views/properties/new.html.erb
<h1>New property</h1>

<%= render "form", property: @property %>

<br>

<div>
  <%= link_to "Back to properties", properties_path %>
</div>

app/views/properties/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @property %>

<div>
  <%= link_to "Edit this property", edit_property_path(@property) %> |
  <%= link_to "Back to properties", properties_path %>

  <%= button_to "Destroy this property", @property, method: :delete %>
</div>

app/views/ratings/_form.html.erb
<%= form_with(model: rating) do |form| %>
  <% if rating.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
        <% rating.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :avg_rating, style: "display: block" %>
    <%= form.text_field :avg_rating %>
  </div>

  <div>
    <%= form.label :location_rating, style: "display: block" %>
    <%= form.text_field :location_rating %>
  </div>

  <div>
    <%= form.label :facilities_rating, style: "display: block" %>
    <%= form.text_field :facilities_rating %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ratings/_rating.html.erb
<div id="<%= dom_id rating %>">
  <p>
    <strong>Avg rating:</strong>
    <%= rating.avg_rating %>
  </p>

  <p>
    <strong>Location rating:</strong>
    <%= rating.location_rating %>
  </p>

  <p>
    <strong>Facilities rating:</strong>
    <%= rating.facilities_rating %>
  </p>

</div>

app/views/ratings/edit.html.erb
<h1>Editing rating</h1>

<%= render "form", rating: @rating %>

<br>

<div>
  <%= link_to "Show this rating", @rating %> |
  <%= link_to "Back to ratings", ratings_path %>
</div>

app/views/ratings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ratings</h1>

<div id="ratings">
  <% @ratings.each do |rating| %>
    <%= render rating %>
    <p>
      <%= link_to "Show this rating", rating %>
    </p>
  <% end %>
</div>

<%= link_to "New rating", new_rating_path %>

app/views/ratings/new.html.erb
<h1>New rating</h1>

<%= render "form", rating: @rating %>

<br>

<div>
  <%= link_to "Back to ratings", ratings_path %>
</div>

app/views/ratings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @rating %>

<div>
  <%= link_to "Edit this rating", edit_rating_path(@rating) %> |
  <%= link_to "Back to ratings", ratings_path %>

  <%= button_to "Destroy this rating", @rating, method: :delete %>
</div>

app/views/welcome/index.html.erb
<%= javascript_include_tag('https://api.mapbox.com/mapbox-gl-js/v2.15.0/mapbox-gl.js') %>
<%= stylesheet_link_tag "https://api.mapbox.com/mapbox-gl-js/v2.15.0/mapbox-gl.css" %>
<div id="app">  
</div> 